---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: instance # molecule-ubi8-init-1
    image: registry.access.redhat.com/ubi8/ubi-init@sha256:75cb1eb60b9636f8daa584c231db552c1de94006778e7224643804a696f04fad
    workingDir: '/tmp'
provisioner:
  inventory:
    group_vars:
      all:
        backup_file_molecule_namespace: ${DEVWORKSPACE_NAMESPACE}
  env:
    ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp
driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: oc
    login_cmd_template: /home/runner/bin/oc exec -it {instance} -c molecule bash