---
- name: Collect Disk Space
  hosts: all
  gather_facts: true
  tasks:
    - name: Run df Command
      ansible.builtin.command: df -h
      register: df_results
      changed_when: false
    - name: Print df Results
      ansible.builtin.debug:
        var: df_results
