---
- name: View Project Environmental Variable
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  tasks:
    - name: Set facts from environmental variables
      ansible.builtin.set_fact:
        project_source: "{{ lookup('ansible.builtin.env', 'PROJECT_SOURCE') }}"
        secondary_source: "{{ lookup('ansible.builtin.env', 'SECONDARY_SOURCE') }}"
        molecule_scenario: "{{ lookup('ansible.builtin.env', 'MOLECULE_SCENARIO') }}"
    - name: Print project environmental variables
      ansible.builtin.debug:
        msg:
          - "PROJECT_SOURCE: {{ project_source }}"
          - "SECONDARY_SOURCE: {{ secondary_source }}"
          - "MOLECULE_SCENARIO: {{ molecule_scenario }}"
